version: '3.7'
services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    hostname: ombi
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.ombi.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.ombi.entrypoints=web-secure"
      - "traefik.http.routers.ombi.middlewares=default-headers@file"
      - "traefik.http.routers.ombi.service=ombi"
      - "traefik.http.routers.ombi.tls=true"
      - "traefik.http.services.ombi.loadbalancer.server.port=3579" # Proxied Port
